# Model arguments
model_name_or_path: Qwen/Qwen3-0.6B
tokenizer_name_or_path: Qwen/Qwen3-0.6B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
use_liger: false
bf16: true
tf32: true
output_dir: runs/Qwen3-0.6B-math-orca-qlora-10k-ep1

# Dataset arguments
dataset_id_or_path: train_dataset.json
max_seq_length: 1024
packing: true
sample_size: 10000  # Explicitly define sample size instead of hard-coding in script

# LoRA arguments
use_peft: true
load_in_4bit: true
lora_target_modules: "all-linear"  # For Qwen3
lora_modules_to_save: ["lm_head", "embed_tokens"]
lora_r: 16
lora_alpha: 16

# Training arguments
num_train_epochs: 1
per_device_train_batch_size: 8
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 2.0e-4
lr_scheduler_type: constant
warmup_ratio: 0.1

# Logging arguments
logging_strategy: steps
logging_steps: 5
report_to:
  - wandb  # Added wandb
save_strategy: "epoch"
seed: 42

# Wandb configuration
wandb_project: "qwen3-finetune"  # Name of your wandb project
wandb_run_name: "Qwen3-0.6B-math-orca-qlora-10k"  # Optional, will be auto-generated if not specified
wandb_tags:  # Optional tags for organizing runs
  - "qwen3"
  - "qlora"
  - "math"

# Hugging Face Hub 
push_to_hub: true
# hub_model_id: Qwen3-0.6B-math-orca-qlora-10k-ep1  # If not defined same as output_dir
hub_strategy: every_save